<?php

namespace Container68Wn6Fl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestBodyArgumentResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.App\ArgumentResolver\RequestBodyArgumentResolver' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/src/ArgumentResolver/RequestBodyArgumentResolver.php';

        return $container->privates['debug.App\\ArgumentResolver\\RequestBodyArgumentResolver'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \App\ArgumentResolver\RequestBodyArgumentResolver(($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')), ($container->services['.container.private.validator'] ?? $container->load('get_Container_Private_ValidatorService'))), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
    }
}
