<?php

namespace ContainerZBxk3eR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDama_Doctrine_Dbal_MiddlewareService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'dama.doctrine.dbal.middleware' shared service.
     *
     * @return \DAMA\DoctrineTestBundle\Doctrine\DBAL\Middleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Driver/Middleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/Middleware.php';

        return $container->privates['dama.doctrine.dbal.middleware'] = new \DAMA\DoctrineTestBundle\Doctrine\DBAL\Middleware();
    }
}
