<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFyMxSml\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFyMxSml/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFyMxSml.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFyMxSml\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFyMxSml\App_KernelTestDebugContainer([
    'container.build_hash' => 'FyMxSml',
    'container.build_id' => '5d3ba97c',
    'container.build_time' => 1666457232,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFyMxSml');
