<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWfq8zEu\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWfq8zEu/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWfq8zEu.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWfq8zEu\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerWfq8zEu\App_KernelTestDebugContainer([
    'container.build_hash' => 'Wfq8zEu',
    'container.build_id' => '149925d9',
    'container.build_time' => 1674319061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWfq8zEu');
