<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTctx00R\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTctx00R/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTctx00R.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTctx00R\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTctx00R\App_KernelTestDebugContainer([
    'container.build_hash' => 'Tctx00R',
    'container.build_id' => 'ca4d135f',
    'container.build_time' => 1671618485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTctx00R');
