<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTK0fU8t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTK0fU8t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTK0fU8t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTK0fU8t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTK0fU8t\App_KernelDevDebugContainer([
    'container.build_hash' => 'TK0fU8t',
    'container.build_id' => 'd4ceedd1',
    'container.build_time' => 1674320502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTK0fU8t');
