<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCK8Wg0J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCK8Wg0J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCK8Wg0J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCK8Wg0J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCK8Wg0J\App_KernelDevDebugContainer([
    'container.build_hash' => 'CK8Wg0J',
    'container.build_id' => '759dd8b3',
    'container.build_time' => 1671616230,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCK8Wg0J');
