<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_bookcategory_categories' => [[], ['_controller' => 'App\\Controller\\BookCategoryController::categories'], [], [['text', '/api/v1/book/categories']], [], [], []],
    'app_book_booksbycategory' => [['id'], ['_controller' => 'App\\Controller\\BookController::booksByCategory'], [], [['text', '/books'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/v1/category']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
];
